# Generated by Django 4.1.2 on 2022-10-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('xid', models.CharField(max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCC', 'success'), ('FAIL', 'fail')], default='FAIL', max_length=4)),
                ('widthdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ENA', 'enabled'), ('DIS', 'disabled')], default='ENA', max_length=3)),
                ('enabled_at', models.DateTimeField(null=True)),
                ('disabled_at', models.DateTimeField(null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('deposit_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCC', 'success'), ('FAIL', 'fail')], default='FAIL', max_length=4)),
                ('deposit_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
